POST http://localhost:3000/posts
Content-Type: application/json

{ "Username":"teste1", "Password":"12345"} 
###
GET http://localhost:3000/

###
GET http://localhost:3000/log
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiY2FpbyIsImlhdCI6MTU4Njk4ODkxMn0.2g2ogT0226OoVhCR9kLeGwhPRonZyV6Rkftd7jlR4Uk

###
POST  http://localhost:3000/login
Content-Type: application/json

{ "username": "caio"} 