POST http://localhost:3000/posts
Content-Type: application/json

{ "Username":"teste1", "Password":"12345"} 
###
GET http://localhost:3000/

###
GET http://localhost:3000/logi
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTIzNDU.2GHDwUKY6-3KFceJzNS2CSr_t24sxSsxTEyMH69atmc


###
POST  http://localhost:3000/login
Content-Type: application/json

{ "Username": "caio"} 